contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'

urlpatterns = [
    path('', views.EmailView.as_view(), name='main'),
]

podcast/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'podcast'

urlpatterns = [
    path('list/', views.PodcastListView.as_view(), name = 'list'),
    path('podcast/<pk>', views.EpisodeListView.as_view(), name='podcast'),
    path('episode/<pk>', views.EpisodeDetailView.as_view(), name = 'episode'),
]

portfolio/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from main_app import views
from django.conf.urls.static import static

"""edit this to match projectname"""
from . import settings



""""the paths for the login and logout are done using the built-in django features"""


urlpatterns = [

    path('admin/', admin.site.urls, name='admin-login'),
    path('', views.post_list, name='post_list'),
    path('post/<pk>', views.post_detail, name = 'post_detail'),
    path('page/<pk>', views.page_detail, name = 'page_detail'),
    path('contact/', include('contact.urls', namespace='contact')),
    path('podcast/', include('podcast.urls', namespace='podcast')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

podcast/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Podcast(models.Model):
    title = models.CharField(max_length = 100)
    url = models.CharField(max_length = 1000)
    language = models.CharField(max_length = 50, default = 'English')
    subtitle = models.CharField(max_length = 100)
    creator = models.CharField(max_length = 100, default = 'Leslie Caminade')
    description = models.CharField(max_length = 200)

    keyword1 = models.CharField(max_length = 50, blank = True)
    keyword2 = models.CharField(max_length = 50, blank = True)
    keyword3 = models.CharField(max_length = 50, blank = True)
    keyword4 = models.CharField(max_length = 50, blank = True)
    keyword5 = models.CharField(max_length = 50, blank = True)
    keyword6 = models.CharField(max_length = 50, blank = True)
    keyword7 = models.CharField(max_length = 50, blank = True)
    keyword8 = models.CharField(max_length = 50, blank = True)
    keyword9 = models.CharField(max_length = 50, blank = True)
    keyword10 = models.CharField(max_length = 50, blank = True)

    email = models.EmailField()
    image = models.ImageField(upload_to = 'podcast/thumbnails')

    category1 = models.CharField(max_length = 50, blank = True)
    category2 = models.CharField(max_length = 50, blank = True)
    category3 = models.CharField(max_length = 50, blank = True)

class Episode(models.Model):
    podcast = models.ForeignKey(Podcast,on_delete = models.CASCADE)
    title = models.CharField(max_length = 50)
    subtitle = models.CharField(max_length = 200)
    description = models.CharField(max_length = 200)
    image = models.ImageField(upload_to = 'podcast/thumbnails')
    length = models.CharField(max_length = 50)
    duration = models.CharField(max_length = 50)
    season = models.CharField(max_length = 10)
    episode = models.CharField(max_length = 10)

    file = models.FileField(upload_to = 'podcast/files')
    published_date = models.DateField(default = timezone.now)
    explicit = models.CharField(max_length = 10 ,default = 'NO')

    def generate_feed(self):
        fg = FeedGenerator()
        fg.id('http://lernfunk.de/media/654321')
        fg.title('Some Testfeed')
        fg.author( {'name':'John Doe','email':'john@example.de'} )
        fg.link( href='http://example.com', rel='alternate' )
        fg.logo('http://ex.com/logo.jpg')
        fg.subtitle('This is a cool feed!')
        fg.link( href='http://larskiesow.de/test.atom', rel='self' )
        fg.language('en')

podcast/views.py
from django.shortcuts import render

# Create your views here.

from django.utils import timezone
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Episode, Podcast
from main_app.models import Post, Page

class PodcastListView(ListView):
    model = Podcast
    paginate_by = 10

    posts_list = Post.objects.order_by('-published_date')
    pages_list = Page.objects.order_by('title')
    extra_context = {
        'posts_list': posts_list,
        'pages_list':pages_list,
    }

class EpisodeListView(ListView):
    #model = Episode
    paginate_by = 10  # if pagination is desired

    posts_list = Post.objects.order_by('-published_date')
    pages_list = Page.objects.order_by('title')
    extra_context = {
        'posts_list': posts_list,
        'pages_list':pages_list,
    }

    def get_queryset(self, **kwargs):
        podcast = Podcast.objects.get(pk = self.kwargs.get('pk'))
        return Episode.objects.filter(podcast = podcast)


class EpisodeDetailView(DetailView):
    model = Episode
    posts_list = Post.objects.order_by('-published_date')
    pages_list = Page.objects.order_by('title')
    extra_context = {
        'posts_list': posts_list,
        'pages_list':pages_list,
    }

podcast/templates/podcast/episode_detail.html
{% extends 'base.html' %}
{% block content %}

<h2>Support this show</h2>
Donation links here


<h1>{{object.title}}</h1>
<p>{{object.published_date}}</p>
<p>{{object.duration}}</p>
<p>{{object.description}}</p>


<h2>Sponsors</h2>
<ul>
  <li>Sponsor 1</li>
  <li>Sponsor 2</li>
  <li>Sponsor 3</li>
</ul>

<h2>Stream this episode</h2>
<p>Put the streaming widget here</p>

<h2>Links and Show Notes</h2>
<ul>
  <li>Link 1</li>
  <li>Link 2</li>
  <li>Link 3</li>
</ul>
{% endblock %}

podcast/templates/podcast/episode_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Podcast Name</h1>
<p>This is a podcast subtitle. This is a short statement the describes what the podcast is all about</p>
<img src="{{episode.podcast.image.url}}" height="100px" alt="">
<h2>Support this show</h2>
<p>This is a place where we put all the donation links</p>

<hr>
<h2>Latest Episodes:</h2>
{% for episode in object_list %}

<div class="list-item">
  <h2><a href="{% url 'podcast:episode' pk=episode.pk %}">{{episode.title}}</a></h2>
  <h3>{{episode.subtitle}}</h3>
  <p class="date" title="">{{episode.published_date}}</p>
  <p>{{episode.duration}}</p>
  <p>{{episode.description|truncatechars:256|safe}}</p>
</div>
{% empty %}
<p>No shows to display yet.</p>
{% endfor %}



<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

podcast/templates/podcast/podcast_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Podcasts</h1>

<hr>
{% for podcast in object_list %}
<div class="list-item">
  <h2><a href="{% url 'podcast:podcast' pk=podcast.pk %}">{{podcast.title}}</a></h2>
  <p>{{podcast.subtitle}}</p>
  <img src="{{podcast.image.url}}" width="200" alt="">
</div>
{% empty %}
<p>No podcasts to display yet.</p>
{% endfor %}



<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}