contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'

urlpatterns = [
    path('', views.EmailView.as_view(), name='main'),
]

podcast/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'podcast'

urlpatterns = [
    path('list/', views.PodcastListView.as_view(), name = 'list'),
    path('podcast/<pk>', views.EpisodeListView.as_view(), name='podcast'),
    path('episode/<pk>', views.EpisodeDetailView.as_view(), name = 'episode'),
]

portfolio/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from main_app import views
from django.conf.urls.static import static

"""edit this to match projectname"""
from . import settings



""""the paths for the login and logout are done using the built-in django features"""


urlpatterns = [

    path('admin/', admin.site.urls, name='admin-login'),
    path('', views.post_list, name='post_list'),
    path('post/<pk>', views.post_detail, name = 'post_detail'),
    path('page/<pk>', views.page_detail, name = 'page_detail'),
    path('contact/', include('contact.urls', namespace='contact')),
    path('podcast/', include('podcast.urls', namespace='podcast')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load  static %}
<html lang="en">
	<head>
		<title>Leslie Caminade</title>

		<meta charset="utf-8" />
		<meta name="description" content="All about Leslie Caminade" />
		<meta name="keywords" content="leslie, caminade, engineer, electronics, ece, ee, review, center, certc, cjc, music, teaching, tutorial" />
		<meta name="author" content="Leslie Caminade" />

		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
		<meta name="color-scheme" content="dark light"/>

    <link rel="stylesheet" href="{%static 'css/normalize.css'%}"/>
    <link rel="stylesheet" href="{%static 'css/style.css'%}"/>
	</head>

	<body>
		<div class="container">
			<header class="header">
				<div class="head-title">
					<h1><a href="http://lesliecaminade.pythonanywhere.com/">Leslie Caminade</a></h1>
					<img src="/media/thumbnail/CGP_leslie_logo2.jpg" width="30" height="30" alt="">
				</div>

				<div class="head-nav">
					<a href="#" id="nav">Menu</a>
				</div>
			</header>

			<aside class="lside" id="lside">
				<div class="block">
					<div class="title">Navigation</div>
					<ul>
						<li><a href="{% url 'post_list' %}">News</a></li>
					</ul>
				</div>

				<div class="block">
					<div class="title">Projects</div>
					<ul>
						{%for page in pages_list%}
            <li><a href="{%url 'page_detail' pk=page.pk%}">{{page.title}}</a></li>
						{%endfor%}
						<li>
							<a href="{%url 'podcast:list'%}">Podcasts</a>
						</li>
          </ul>
				</div>

				<div class="block">
					<div class="title">Contacts</div>

					<ul>
						{%include 'main_app/handles.html'%}
					</ul>

				</div>

				<div class="block">
					<div class="title">Donation</div>

					<ul>
						<li><a href="https://www.patreon.com/lesliecaminade" target="_blank" rel="nofollow" title="Content creation is powered by your donations!">Patreon</a></li>
					</ul>
				</div>
			</aside>

			<div class="space"></div>

			<main class="content">
				{%block content%}
				{% endblock %}
			</main>

			<footer class="footer">
				<p>(c) 2009-2020 Leslie Caminade. All rights reserved.</p>
			</footer>
		</div>

		<script type="text/javascript">
			document.getElementById('nav').addEventListener("click", function(e) {
				(function(e) {
					document.getElementById('lside').classList.toggle("lside-show"); return false;
				}).call(document.getElementById('nav'), e);
			});
		</script>
	</body>
</html>

<!-- old-school in my blood, 2011 comming back (15/10/15) -->
<!-- upd: (26/07/17) -->